// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: cs.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoId int32

const (
	ProtoId_login_req_id                 ProtoId = 1
	ProtoId_login_resp_id                ProtoId = 2
	ProtoId_get_all_room_list_req_id     ProtoId = 1001
	ProtoId_get_all_room_list_resp_id    ProtoId = 1002
	ProtoId_create_room_req_id           ProtoId = 1003
	ProtoId_create_room_resp_id          ProtoId = 1004
	ProtoId_dismiss_room_req_id          ProtoId = 1005
	ProtoId_dismiss_room_resp_id         ProtoId = 1006
	ProtoId_change_room_settings_req_id  ProtoId = 1007
	ProtoId_change_room_settings_resp_id ProtoId = 1008
	ProtoId_change_room_settings_ntf_id  ProtoId = 1009
	ProtoId_join_room_req_id             ProtoId = 2001
	ProtoId_join_room_resp_id            ProtoId = 2002
	ProtoId_change_join_settings_req_id  ProtoId = 2003
	ProtoId_change_join_settings_resp_id ProtoId = 2004
	ProtoId_send_info_req_id             ProtoId = 2005
	ProtoId_send_info_resp_id            ProtoId = 2006
	ProtoId_recv_info_ntf_id             ProtoId = 2007
	ProtoId_exit_room_req_id             ProtoId = 2008
	ProtoId_exit_room_resp_id            ProtoId = 2009
	ProtoId_get_room_all_member_req_id   ProtoId = 2010
	ProtoId_get_room_all_member_resp_id  ProtoId = 2011
)

// Enum value maps for ProtoId.
var (
	ProtoId_name = map[int32]string{
		1:    "login_req_id",
		2:    "login_resp_id",
		1001: "get_all_room_list_req_id",
		1002: "get_all_room_list_resp_id",
		1003: "create_room_req_id",
		1004: "create_room_resp_id",
		1005: "dismiss_room_req_id",
		1006: "dismiss_room_resp_id",
		1007: "change_room_settings_req_id",
		1008: "change_room_settings_resp_id",
		1009: "change_room_settings_ntf_id",
		2001: "join_room_req_id",
		2002: "join_room_resp_id",
		2003: "change_join_settings_req_id",
		2004: "change_join_settings_resp_id",
		2005: "send_info_req_id",
		2006: "send_info_resp_id",
		2007: "recv_info_ntf_id",
		2008: "exit_room_req_id",
		2009: "exit_room_resp_id",
		2010: "get_room_all_member_req_id",
		2011: "get_room_all_member_resp_id",
	}
	ProtoId_value = map[string]int32{
		"login_req_id":                 1,
		"login_resp_id":                2,
		"get_all_room_list_req_id":     1001,
		"get_all_room_list_resp_id":    1002,
		"create_room_req_id":           1003,
		"create_room_resp_id":          1004,
		"dismiss_room_req_id":          1005,
		"dismiss_room_resp_id":         1006,
		"change_room_settings_req_id":  1007,
		"change_room_settings_resp_id": 1008,
		"change_room_settings_ntf_id":  1009,
		"join_room_req_id":             2001,
		"join_room_resp_id":            2002,
		"change_join_settings_req_id":  2003,
		"change_join_settings_resp_id": 2004,
		"send_info_req_id":             2005,
		"send_info_resp_id":            2006,
		"recv_info_ntf_id":             2007,
		"exit_room_req_id":             2008,
		"exit_room_resp_id":            2009,
		"get_room_all_member_req_id":   2010,
		"get_room_all_member_resp_id":  2011,
	}
)

func (x ProtoId) Enum() *ProtoId {
	p := new(ProtoId)
	*p = x
	return p
}

func (x ProtoId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtoId) Descriptor() protoreflect.EnumDescriptor {
	return file_cs_proto_enumTypes[0].Descriptor()
}

func (ProtoId) Type() protoreflect.EnumType {
	return &file_cs_proto_enumTypes[0]
}

func (x ProtoId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ProtoId) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ProtoId(num)
	return nil
}

// Deprecated: Use ProtoId.Descriptor instead.
func (ProtoId) EnumDescriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{0}
}

type ErrorId int32

const (
	ErrorId_err_none                           ErrorId = 0
	ErrorId_err_unknown                        ErrorId = 1
	ErrorId_err_parsing_proto                  ErrorId = 2
	ErrorId_err_room_name_invalid              ErrorId = 1001
	ErrorId_err_room_id_not_exist              ErrorId = 1002
	ErrorId_err_opt_disallowed_not_room_holder ErrorId = 1003
	ErrorId_err_join_room_name_invalid         ErrorId = 2001
	ErrorId_err_join_room_close                ErrorId = 2002
	ErrorId_err_reconn_too_late                ErrorId = 3001
)

// Enum value maps for ErrorId.
var (
	ErrorId_name = map[int32]string{
		0:    "err_none",
		1:    "err_unknown",
		2:    "err_parsing_proto",
		1001: "err_room_name_invalid",
		1002: "err_room_id_not_exist",
		1003: "err_opt_disallowed_not_room_holder",
		2001: "err_join_room_name_invalid",
		2002: "err_join_room_close",
		3001: "err_reconn_too_late",
	}
	ErrorId_value = map[string]int32{
		"err_none":                           0,
		"err_unknown":                        1,
		"err_parsing_proto":                  2,
		"err_room_name_invalid":              1001,
		"err_room_id_not_exist":              1002,
		"err_opt_disallowed_not_room_holder": 1003,
		"err_join_room_name_invalid":         2001,
		"err_join_room_close":                2002,
		"err_reconn_too_late":                3001,
	}
)

func (x ErrorId) Enum() *ErrorId {
	p := new(ErrorId)
	*p = x
	return p
}

func (x ErrorId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorId) Descriptor() protoreflect.EnumDescriptor {
	return file_cs_proto_enumTypes[1].Descriptor()
}

func (ErrorId) Type() protoreflect.EnumType {
	return &file_cs_proto_enumTypes[1]
}

func (x ErrorId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ErrorId) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ErrorId(num)
	return nil
}

// Deprecated: Use ErrorId.Descriptor instead.
func (ErrorId) EnumDescriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{1}
}

type LoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       *ProtoId `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=1" json:"id,omitempty"`
	Auth     *string  `protobuf:"bytes,2,opt,name=auth" json:"auth,omitempty"`
	IsReconn *bool    `protobuf:"varint,3,opt,name=is_reconn,json=isReconn" json:"is_reconn,omitempty"`
}

// Default values for LoginReq fields.
const (
	Default_LoginReq_Id = ProtoId_login_req_id
)

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{0}
}

func (x *LoginReq) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_LoginReq_Id
}

func (x *LoginReq) GetAuth() string {
	if x != nil && x.Auth != nil {
		return *x.Auth
	}
	return ""
}

func (x *LoginReq) GetIsReconn() bool {
	if x != nil && x.IsReconn != nil {
		return *x.IsReconn
	}
	return false
}

type LoginResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    *ProtoId `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=2" json:"id,omitempty"`
	Error *ErrorId `protobuf:"varint,2,opt,name=error,enum=main.ErrorId" json:"error,omitempty"`
	Auth  *string  `protobuf:"bytes,3,opt,name=auth" json:"auth,omitempty"`
}

// Default values for LoginResp fields.
const (
	Default_LoginResp_Id = ProtoId_login_resp_id
)

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResp) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_LoginResp_Id
}

func (x *LoginResp) GetError() ErrorId {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ErrorId_err_none
}

func (x *LoginResp) GetAuth() string {
	if x != nil && x.Auth != nil {
		return *x.Auth
	}
	return ""
}

type GetAllRoomListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *ProtoId `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=1001" json:"id,omitempty"`
}

// Default values for GetAllRoomListReq fields.
const (
	Default_GetAllRoomListReq_Id = ProtoId_get_all_room_list_req_id
)

func (x *GetAllRoomListReq) Reset() {
	*x = GetAllRoomListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllRoomListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRoomListReq) ProtoMessage() {}

func (x *GetAllRoomListReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRoomListReq.ProtoReflect.Descriptor instead.
func (*GetAllRoomListReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllRoomListReq) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_GetAllRoomListReq_Id
}

type GetAllRoomListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    *ProtoId        `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=1002" json:"id,omitempty"`
	Rooms []*RoomSettings `protobuf:"bytes,2,rep,name=rooms" json:"rooms,omitempty"`
}

// Default values for GetAllRoomListResp fields.
const (
	Default_GetAllRoomListResp_Id = ProtoId_get_all_room_list_resp_id
)

func (x *GetAllRoomListResp) Reset() {
	*x = GetAllRoomListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllRoomListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRoomListResp) ProtoMessage() {}

func (x *GetAllRoomListResp) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRoomListResp.ProtoReflect.Descriptor instead.
func (*GetAllRoomListResp) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllRoomListResp) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_GetAllRoomListResp_Id
}

func (x *GetAllRoomListResp) GetRooms() []*RoomSettings {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type CreateRoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       *ProtoId      `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=1003" json:"id,omitempty"`
	Settings *RoomSettings `protobuf:"bytes,2,opt,name=settings" json:"settings,omitempty"`
}

// Default values for CreateRoomReq fields.
const (
	Default_CreateRoomReq_Id = ProtoId_create_room_req_id
)

func (x *CreateRoomReq) Reset() {
	*x = CreateRoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomReq) ProtoMessage() {}

func (x *CreateRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomReq.ProtoReflect.Descriptor instead.
func (*CreateRoomReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRoomReq) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_CreateRoomReq_Id
}

func (x *CreateRoomReq) GetSettings() *RoomSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type RoomSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId   *int32  `protobuf:"varint,1,opt,name=room_id,json=roomId" json:"room_id,omitempty"`
	RoomName *string `protobuf:"bytes,2,opt,name=room_name,json=roomName" json:"room_name,omitempty"`
	Open     *bool   `protobuf:"varint,3,opt,name=open,def=1" json:"open,omitempty"`
}

// Default values for RoomSettings fields.
const (
	Default_RoomSettings_Open = bool(true)
)

func (x *RoomSettings) Reset() {
	*x = RoomSettings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomSettings) ProtoMessage() {}

func (x *RoomSettings) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomSettings.ProtoReflect.Descriptor instead.
func (*RoomSettings) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{5}
}

func (x *RoomSettings) GetRoomId() int32 {
	if x != nil && x.RoomId != nil {
		return *x.RoomId
	}
	return 0
}

func (x *RoomSettings) GetRoomName() string {
	if x != nil && x.RoomName != nil {
		return *x.RoomName
	}
	return ""
}

func (x *RoomSettings) GetOpen() bool {
	if x != nil && x.Open != nil {
		return *x.Open
	}
	return Default_RoomSettings_Open
}

type CreateRoomResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        *ProtoId `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=1004" json:"id,omitempty"`
	NewRoomId *int32   `protobuf:"varint,2,opt,name=new_room_id,json=newRoomId" json:"new_room_id,omitempty"`
	Error     *ErrorId `protobuf:"varint,3,opt,name=error,enum=main.ErrorId" json:"error,omitempty"`
}

// Default values for CreateRoomResp fields.
const (
	Default_CreateRoomResp_Id = ProtoId_create_room_resp_id
)

func (x *CreateRoomResp) Reset() {
	*x = CreateRoomResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResp) ProtoMessage() {}

func (x *CreateRoomResp) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResp.ProtoReflect.Descriptor instead.
func (*CreateRoomResp) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRoomResp) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_CreateRoomResp_Id
}

func (x *CreateRoomResp) GetNewRoomId() int32 {
	if x != nil && x.NewRoomId != nil {
		return *x.NewRoomId
	}
	return 0
}

func (x *CreateRoomResp) GetError() ErrorId {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ErrorId_err_none
}

type DismissRoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     *ProtoId `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=1005" json:"id,omitempty"`
	RoomId *int32   `protobuf:"varint,2,opt,name=room_id,json=roomId" json:"room_id,omitempty"`
}

// Default values for DismissRoomReq fields.
const (
	Default_DismissRoomReq_Id = ProtoId_dismiss_room_req_id
)

func (x *DismissRoomReq) Reset() {
	*x = DismissRoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DismissRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DismissRoomReq) ProtoMessage() {}

func (x *DismissRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DismissRoomReq.ProtoReflect.Descriptor instead.
func (*DismissRoomReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{7}
}

func (x *DismissRoomReq) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_DismissRoomReq_Id
}

func (x *DismissRoomReq) GetRoomId() int32 {
	if x != nil && x.RoomId != nil {
		return *x.RoomId
	}
	return 0
}

type DismissRoomResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    *ProtoId `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=1006" json:"id,omitempty"`
	Error *ErrorId `protobuf:"varint,2,opt,name=error,enum=main.ErrorId" json:"error,omitempty"`
}

// Default values for DismissRoomResp fields.
const (
	Default_DismissRoomResp_Id = ProtoId_dismiss_room_resp_id
)

func (x *DismissRoomResp) Reset() {
	*x = DismissRoomResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DismissRoomResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DismissRoomResp) ProtoMessage() {}

func (x *DismissRoomResp) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DismissRoomResp.ProtoReflect.Descriptor instead.
func (*DismissRoomResp) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{8}
}

func (x *DismissRoomResp) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_DismissRoomResp_Id
}

func (x *DismissRoomResp) GetError() ErrorId {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ErrorId_err_none
}

type ChangeRoomSettingsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       *ProtoId      `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=1007" json:"id,omitempty"`
	RoomId   *int32        `protobuf:"varint,2,opt,name=room_id,json=roomId" json:"room_id,omitempty"`
	Settings *RoomSettings `protobuf:"bytes,3,opt,name=settings" json:"settings,omitempty"`
}

// Default values for ChangeRoomSettingsReq fields.
const (
	Default_ChangeRoomSettingsReq_Id = ProtoId_change_room_settings_req_id
)

func (x *ChangeRoomSettingsReq) Reset() {
	*x = ChangeRoomSettingsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeRoomSettingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeRoomSettingsReq) ProtoMessage() {}

func (x *ChangeRoomSettingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeRoomSettingsReq.ProtoReflect.Descriptor instead.
func (*ChangeRoomSettingsReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{9}
}

func (x *ChangeRoomSettingsReq) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_ChangeRoomSettingsReq_Id
}

func (x *ChangeRoomSettingsReq) GetRoomId() int32 {
	if x != nil && x.RoomId != nil {
		return *x.RoomId
	}
	return 0
}

func (x *ChangeRoomSettingsReq) GetSettings() *RoomSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type ChangeRoomSettingsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    *ProtoId `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=1008" json:"id,omitempty"`
	Error *ErrorId `protobuf:"varint,2,opt,name=error,enum=main.ErrorId" json:"error,omitempty"`
}

// Default values for ChangeRoomSettingsResp fields.
const (
	Default_ChangeRoomSettingsResp_Id = ProtoId_change_room_settings_resp_id
)

func (x *ChangeRoomSettingsResp) Reset() {
	*x = ChangeRoomSettingsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeRoomSettingsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeRoomSettingsResp) ProtoMessage() {}

func (x *ChangeRoomSettingsResp) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeRoomSettingsResp.ProtoReflect.Descriptor instead.
func (*ChangeRoomSettingsResp) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{10}
}

func (x *ChangeRoomSettingsResp) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_ChangeRoomSettingsResp_Id
}

func (x *ChangeRoomSettingsResp) GetError() ErrorId {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ErrorId_err_none
}

type ChangeRoomSettingsNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       *ProtoId      `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=1009" json:"id,omitempty"`
	RoomId   *int32        `protobuf:"varint,2,opt,name=room_id,json=roomId" json:"room_id,omitempty"`
	Settings *RoomSettings `protobuf:"bytes,3,opt,name=settings" json:"settings,omitempty"`
}

// Default values for ChangeRoomSettingsNtf fields.
const (
	Default_ChangeRoomSettingsNtf_Id = ProtoId_change_room_settings_ntf_id
)

func (x *ChangeRoomSettingsNtf) Reset() {
	*x = ChangeRoomSettingsNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeRoomSettingsNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeRoomSettingsNtf) ProtoMessage() {}

func (x *ChangeRoomSettingsNtf) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeRoomSettingsNtf.ProtoReflect.Descriptor instead.
func (*ChangeRoomSettingsNtf) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{11}
}

func (x *ChangeRoomSettingsNtf) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_ChangeRoomSettingsNtf_Id
}

func (x *ChangeRoomSettingsNtf) GetRoomId() int32 {
	if x != nil && x.RoomId != nil {
		return *x.RoomId
	}
	return 0
}

func (x *ChangeRoomSettingsNtf) GetSettings() *RoomSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type JoinRoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       *ProtoId      `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=2001" json:"id,omitempty"`
	RoomId   *int32        `protobuf:"varint,2,opt,name=room_id,json=roomId" json:"room_id,omitempty"`
	Settings *JoinSettings `protobuf:"bytes,3,opt,name=settings" json:"settings,omitempty"`
}

// Default values for JoinRoomReq fields.
const (
	Default_JoinRoomReq_Id = ProtoId_join_room_req_id
)

func (x *JoinRoomReq) Reset() {
	*x = JoinRoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomReq) ProtoMessage() {}

func (x *JoinRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomReq.ProtoReflect.Descriptor instead.
func (*JoinRoomReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{12}
}

func (x *JoinRoomReq) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_JoinRoomReq_Id
}

func (x *JoinRoomReq) GetRoomId() int32 {
	if x != nil && x.RoomId != nil {
		return *x.RoomId
	}
	return 0
}

func (x *JoinRoomReq) GetSettings() *JoinSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type JoinSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JoinName *string `protobuf:"bytes,1,opt,name=join_name,json=joinName" json:"join_name,omitempty"`
}

func (x *JoinSettings) Reset() {
	*x = JoinSettings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinSettings) ProtoMessage() {}

func (x *JoinSettings) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinSettings.ProtoReflect.Descriptor instead.
func (*JoinSettings) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{13}
}

func (x *JoinSettings) GetJoinName() string {
	if x != nil && x.JoinName != nil {
		return *x.JoinName
	}
	return ""
}

type GetRoomAllMemberReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     *ProtoId `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=2010" json:"id,omitempty"`
	RoomId *int32   `protobuf:"varint,2,opt,name=room_id,json=roomId" json:"room_id,omitempty"`
}

// Default values for GetRoomAllMemberReq fields.
const (
	Default_GetRoomAllMemberReq_Id = ProtoId_get_room_all_member_req_id
)

func (x *GetRoomAllMemberReq) Reset() {
	*x = GetRoomAllMemberReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomAllMemberReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomAllMemberReq) ProtoMessage() {}

func (x *GetRoomAllMemberReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomAllMemberReq.ProtoReflect.Descriptor instead.
func (*GetRoomAllMemberReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{14}
}

func (x *GetRoomAllMemberReq) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_GetRoomAllMemberReq_Id
}

func (x *GetRoomAllMemberReq) GetRoomId() int32 {
	if x != nil && x.RoomId != nil {
		return *x.RoomId
	}
	return 0
}

type GetRoomAllMemberResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        *ProtoId `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=2011" json:"id,omitempty"`
	JoinNames []string `protobuf:"bytes,2,rep,name=join_names,json=joinNames" json:"join_names,omitempty"`
}

// Default values for GetRoomAllMemberResp fields.
const (
	Default_GetRoomAllMemberResp_Id = ProtoId_get_room_all_member_resp_id
)

func (x *GetRoomAllMemberResp) Reset() {
	*x = GetRoomAllMemberResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoomAllMemberResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomAllMemberResp) ProtoMessage() {}

func (x *GetRoomAllMemberResp) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomAllMemberResp.ProtoReflect.Descriptor instead.
func (*GetRoomAllMemberResp) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{15}
}

func (x *GetRoomAllMemberResp) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_GetRoomAllMemberResp_Id
}

func (x *GetRoomAllMemberResp) GetJoinNames() []string {
	if x != nil {
		return x.JoinNames
	}
	return nil
}

type JoinRoomResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    *ProtoId `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=2002" json:"id,omitempty"`
	Error *ErrorId `protobuf:"varint,2,opt,name=error,enum=main.ErrorId" json:"error,omitempty"`
}

// Default values for JoinRoomResp fields.
const (
	Default_JoinRoomResp_Id = ProtoId_join_room_resp_id
)

func (x *JoinRoomResp) Reset() {
	*x = JoinRoomResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRoomResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomResp) ProtoMessage() {}

func (x *JoinRoomResp) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomResp.ProtoReflect.Descriptor instead.
func (*JoinRoomResp) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{16}
}

func (x *JoinRoomResp) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_JoinRoomResp_Id
}

func (x *JoinRoomResp) GetError() ErrorId {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ErrorId_err_none
}

type ChangeJoinSettingsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       *ProtoId      `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=2003" json:"id,omitempty"`
	Settings *JoinSettings `protobuf:"bytes,3,opt,name=settings" json:"settings,omitempty"`
}

// Default values for ChangeJoinSettingsReq fields.
const (
	Default_ChangeJoinSettingsReq_Id = ProtoId_change_join_settings_req_id
)

func (x *ChangeJoinSettingsReq) Reset() {
	*x = ChangeJoinSettingsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeJoinSettingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeJoinSettingsReq) ProtoMessage() {}

func (x *ChangeJoinSettingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeJoinSettingsReq.ProtoReflect.Descriptor instead.
func (*ChangeJoinSettingsReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{17}
}

func (x *ChangeJoinSettingsReq) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_ChangeJoinSettingsReq_Id
}

func (x *ChangeJoinSettingsReq) GetSettings() *JoinSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type ChangeJoinSettingsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    *ProtoId `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=2004" json:"id,omitempty"`
	Error *ErrorId `protobuf:"varint,2,opt,name=error,enum=main.ErrorId" json:"error,omitempty"`
}

// Default values for ChangeJoinSettingsResp fields.
const (
	Default_ChangeJoinSettingsResp_Id = ProtoId_change_join_settings_resp_id
)

func (x *ChangeJoinSettingsResp) Reset() {
	*x = ChangeJoinSettingsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeJoinSettingsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeJoinSettingsResp) ProtoMessage() {}

func (x *ChangeJoinSettingsResp) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeJoinSettingsResp.ProtoReflect.Descriptor instead.
func (*ChangeJoinSettingsResp) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{18}
}

func (x *ChangeJoinSettingsResp) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_ChangeJoinSettingsResp_Id
}

func (x *ChangeJoinSettingsResp) GetError() ErrorId {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ErrorId_err_none
}

type SendInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     *ProtoId `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=2005" json:"id,omitempty"`
	RoomId *int32   `protobuf:"varint,2,opt,name=room_id,json=roomId" json:"room_id,omitempty"`
	Info   *string  `protobuf:"bytes,3,opt,name=info" json:"info,omitempty"`
}

// Default values for SendInfoReq fields.
const (
	Default_SendInfoReq_Id = ProtoId_send_info_req_id
)

func (x *SendInfoReq) Reset() {
	*x = SendInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendInfoReq) ProtoMessage() {}

func (x *SendInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendInfoReq.ProtoReflect.Descriptor instead.
func (*SendInfoReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{19}
}

func (x *SendInfoReq) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_SendInfoReq_Id
}

func (x *SendInfoReq) GetRoomId() int32 {
	if x != nil && x.RoomId != nil {
		return *x.RoomId
	}
	return 0
}

func (x *SendInfoReq) GetInfo() string {
	if x != nil && x.Info != nil {
		return *x.Info
	}
	return ""
}

type SendInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    *ProtoId `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=2006" json:"id,omitempty"`
	Error *ErrorId `protobuf:"varint,2,opt,name=error,enum=main.ErrorId" json:"error,omitempty"`
}

// Default values for SendInfoResp fields.
const (
	Default_SendInfoResp_Id = ProtoId_send_info_resp_id
)

func (x *SendInfoResp) Reset() {
	*x = SendInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendInfoResp) ProtoMessage() {}

func (x *SendInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendInfoResp.ProtoReflect.Descriptor instead.
func (*SendInfoResp) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{20}
}

func (x *SendInfoResp) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_SendInfoResp_Id
}

func (x *SendInfoResp) GetError() ErrorId {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ErrorId_err_none
}

type RecvInfoNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         *ProtoId `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=2007" json:"id,omitempty"`
	RoomId     *int32   `protobuf:"varint,2,opt,name=room_id,json=roomId" json:"room_id,omitempty"`
	SenderName *string  `protobuf:"bytes,3,opt,name=sender_name,json=senderName" json:"sender_name,omitempty"`
	Msg        *string  `protobuf:"bytes,4,opt,name=msg" json:"msg,omitempty"`
}

// Default values for RecvInfoNtf fields.
const (
	Default_RecvInfoNtf_Id = ProtoId_recv_info_ntf_id
)

func (x *RecvInfoNtf) Reset() {
	*x = RecvInfoNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecvInfoNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecvInfoNtf) ProtoMessage() {}

func (x *RecvInfoNtf) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecvInfoNtf.ProtoReflect.Descriptor instead.
func (*RecvInfoNtf) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{21}
}

func (x *RecvInfoNtf) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_RecvInfoNtf_Id
}

func (x *RecvInfoNtf) GetRoomId() int32 {
	if x != nil && x.RoomId != nil {
		return *x.RoomId
	}
	return 0
}

func (x *RecvInfoNtf) GetSenderName() string {
	if x != nil && x.SenderName != nil {
		return *x.SenderName
	}
	return ""
}

func (x *RecvInfoNtf) GetMsg() string {
	if x != nil && x.Msg != nil {
		return *x.Msg
	}
	return ""
}

type ExitRoomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     *ProtoId `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=2008" json:"id,omitempty"`
	RoomId *int32   `protobuf:"varint,2,opt,name=room_id,json=roomId" json:"room_id,omitempty"`
}

// Default values for ExitRoomReq fields.
const (
	Default_ExitRoomReq_Id = ProtoId_exit_room_req_id
)

func (x *ExitRoomReq) Reset() {
	*x = ExitRoomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExitRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitRoomReq) ProtoMessage() {}

func (x *ExitRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitRoomReq.ProtoReflect.Descriptor instead.
func (*ExitRoomReq) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{22}
}

func (x *ExitRoomReq) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_ExitRoomReq_Id
}

func (x *ExitRoomReq) GetRoomId() int32 {
	if x != nil && x.RoomId != nil {
		return *x.RoomId
	}
	return 0
}

type ExitRoomResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    *ProtoId `protobuf:"varint,1,opt,name=id,enum=main.ProtoId,def=2009" json:"id,omitempty"`
	Error *ErrorId `protobuf:"varint,2,opt,name=error,enum=main.ErrorId" json:"error,omitempty"`
}

// Default values for ExitRoomResp fields.
const (
	Default_ExitRoomResp_Id = ProtoId_exit_room_resp_id
)

func (x *ExitRoomResp) Reset() {
	*x = ExitRoomResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cs_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExitRoomResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitRoomResp) ProtoMessage() {}

func (x *ExitRoomResp) ProtoReflect() protoreflect.Message {
	mi := &file_cs_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitRoomResp.ProtoReflect.Descriptor instead.
func (*ExitRoomResp) Descriptor() ([]byte, []int) {
	return file_cs_proto_rawDescGZIP(), []int{23}
}

func (x *ExitRoomResp) GetId() ProtoId {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return Default_ExitRoomResp_Id
}

func (x *ExitRoomResp) GetError() ErrorId {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ErrorId_err_none
}

var File_cs_proto protoreflect.FileDescriptor

var file_cs_proto_rawDesc = []byte{
	0x0a, 0x08, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e,
	0x22, 0x6a, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x2c, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x3a, 0x0c, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x5f, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61,
	0x75, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x12,
	0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x6e, 0x22, 0x75, 0x0a, 0x0a,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x12, 0x2d, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x3a, 0x0d, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x72, 0x65,
	0x73, 0x70, 0x5f, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61,
	0x75, 0x74, 0x68, 0x22, 0x51, 0x0a, 0x15, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x6c, 0x6c, 0x5f, 0x72,
	0x6f, 0x6f, 0x6d, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x38, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x3a, 0x18, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x6c,
	0x6c, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x5f,
	0x69, 0x64, 0x52, 0x02, 0x69, 0x64, 0x22, 0x7e, 0x0a, 0x16, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x6c,
	0x6c, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x70,
	0x12, 0x39, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x3a, 0x19, 0x67, 0x65,
	0x74, 0x5f, 0x61, 0x6c, 0x6c, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f,
	0x72, 0x65, 0x73, 0x70, 0x5f, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x29, 0x0a, 0x05, 0x72,
	0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52,
	0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x22, 0x76, 0x0a, 0x0f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x32, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x5f, 0x69, 0x64, 0x3a, 0x12, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x6f,
	0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2f, 0x0a,
	0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x52, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x5f,
	0x0a, 0x0d, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12,
	0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6f, 0x6d,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6f,
	0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x3a, 0x04, 0x74, 0x72, 0x75, 0x65, 0x52, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x22,
	0x8d, 0x01, 0x0a, 0x10, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f,
	0x72, 0x65, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x69, 0x64,
	0x3a, 0x13, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65,
	0x73, 0x70, 0x5f, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0b, 0x6e, 0x65, 0x77,
	0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x6e, 0x65, 0x77, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22,
	0x60, 0x0a, 0x10, 0x64, 0x69, 0x73, 0x6d, 0x69, 0x73, 0x73, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f,
	0x72, 0x65, 0x71, 0x12, 0x33, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x3a,
	0x13, 0x64, 0x69, 0x73, 0x6d, 0x69, 0x73, 0x73, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65,
	0x71, 0x5f, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49,
	0x64, 0x22, 0x6f, 0x0a, 0x11, 0x64, 0x69, 0x73, 0x6d, 0x69, 0x73, 0x73, 0x5f, 0x72, 0x6f, 0x6f,
	0x6d, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x12, 0x34, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f,
	0x69, 0x64, 0x3a, 0x14, 0x64, 0x69, 0x73, 0x6d, 0x69, 0x73, 0x73, 0x5f, 0x72, 0x6f, 0x6f, 0x6d,
	0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0xa1, 0x01, 0x0a, 0x18, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x72, 0x6f,
	0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x72, 0x65, 0x71, 0x12,
	0x3b, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x3a, 0x1b, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72,
	0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x72,
	0x6f, 0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x08, 0x73, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x7f, 0x0a, 0x19, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x72,
	0x65, 0x73, 0x70, 0x12, 0x3c, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x3a,
	0x1c, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x69, 0x64, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x24, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x69, 0x64,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xa1, 0x01, 0x0a, 0x18, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x5f, 0x6e, 0x74, 0x66, 0x12, 0x3b, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x69, 0x64,
	0x3a, 0x1b, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x73, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x6e, 0x74, 0x66, 0x5f, 0x69, 0x64, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x08, 0x73, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x52, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x8b, 0x01, 0x0a, 0x0d,
	0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x30, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x3a, 0x10, 0x6a, 0x6f, 0x69, 0x6e, 0x5f,
	0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x08, 0x73, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x2e, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52,
	0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x2c, 0x0a, 0x0d, 0x6a, 0x6f, 0x69,
	0x6e, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6a, 0x6f,
	0x69, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6a,
	0x6f, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x6e, 0x0a, 0x17, 0x67, 0x65, 0x74, 0x5f, 0x72,
	0x6f, 0x6f, 0x6d, 0x5f, 0x61, 0x6c, 0x6c, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x72,
	0x65, 0x71, 0x12, 0x3a, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x3a, 0x1a,
	0x67, 0x65, 0x74, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x61, 0x6c, 0x6c, 0x5f, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x76, 0x0a, 0x18, 0x67, 0x65, 0x74, 0x5f, 0x72,
	0x6f, 0x6f, 0x6d, 0x5f, 0x61, 0x6c, 0x6c, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x72,
	0x65, 0x73, 0x70, 0x12, 0x3b, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x3a,
	0x1b, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x61, 0x6c, 0x6c, 0x5f, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x6a, 0x6f, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x22,
	0x69, 0x0a, 0x0e, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x12, 0x31, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e,
	0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x3a, 0x11, 0x6a,
	0x6f, 0x69, 0x6e, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x69, 0x64,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x5f, 0x69, 0x64, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x88, 0x01, 0x0a, 0x18, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x3b, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x5f, 0x69, 0x64, 0x3a, 0x1b, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x6a, 0x6f, 0x69, 0x6e,
	0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x2f, 0x0a, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x6a, 0x6f,
	0x69, 0x6e, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x08, 0x73, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x7f, 0x0a, 0x19, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f,
	0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x72, 0x65,
	0x73, 0x70, 0x12, 0x3c, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x3a, 0x1c,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x24, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x6e, 0x0a, 0x0d, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x30, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x5f, 0x69, 0x64, 0x3a, 0x10, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x72,
	0x65, 0x71, 0x5f, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f,
	0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x69, 0x0a, 0x0e, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x12, 0x31, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x5f, 0x69, 0x64, 0x3a, 0x11, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f,
	0x72, 0x65, 0x73, 0x70, 0x5f, 0x69, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x22, 0x8d, 0x01, 0x0a, 0x0d, 0x72, 0x65, 0x63, 0x76, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f,
	0x6e, 0x74, 0x66, 0x12, 0x30, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x3a,
	0x10, 0x72, 0x65, 0x63, 0x76, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x6e, 0x74, 0x66, 0x5f, 0x69,
	0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x22, 0x5a, 0x0a, 0x0d, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72,
	0x65, 0x71, 0x12, 0x30, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x3a, 0x10,
	0x65, 0x78, 0x69, 0x74, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x69, 0x0a,
	0x0e, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x12,
	0x31, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x69, 0x64, 0x3a, 0x11, 0x65, 0x78, 0x69,
	0x74, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x69, 0x64, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x24, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x69,
	0x64, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2a, 0xe9, 0x04, 0x0a, 0x08, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x5f, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x0c, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x72,
	0x65, 0x71, 0x5f, 0x69, 0x64, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x69, 0x64, 0x10, 0x02, 0x12, 0x1d, 0x0a, 0x18, 0x67, 0x65,
	0x74, 0x5f, 0x61, 0x6c, 0x6c, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f,
	0x72, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x10, 0xe9, 0x07, 0x12, 0x1e, 0x0a, 0x19, 0x67, 0x65, 0x74,
	0x5f, 0x61, 0x6c, 0x6c, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x72,
	0x65, 0x73, 0x70, 0x5f, 0x69, 0x64, 0x10, 0xea, 0x07, 0x12, 0x17, 0x0a, 0x12, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x10,
	0xeb, 0x07, 0x12, 0x18, 0x0a, 0x13, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x6f, 0x6f,
	0x6d, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x69, 0x64, 0x10, 0xec, 0x07, 0x12, 0x18, 0x0a, 0x13,
	0x64, 0x69, 0x73, 0x6d, 0x69, 0x73, 0x73, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x71,
	0x5f, 0x69, 0x64, 0x10, 0xed, 0x07, 0x12, 0x19, 0x0a, 0x14, 0x64, 0x69, 0x73, 0x6d, 0x69, 0x73,
	0x73, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x69, 0x64, 0x10, 0xee,
	0x07, 0x12, 0x20, 0x0a, 0x1b, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x6d,
	0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64,
	0x10, 0xef, 0x07, 0x12, 0x21, 0x0a, 0x1c, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x72, 0x6f,
	0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x70,
	0x5f, 0x69, 0x64, 0x10, 0xf0, 0x07, 0x12, 0x20, 0x0a, 0x1b, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x6e,
	0x74, 0x66, 0x5f, 0x69, 0x64, 0x10, 0xf1, 0x07, 0x12, 0x15, 0x0a, 0x10, 0x6a, 0x6f, 0x69, 0x6e,
	0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x10, 0xd1, 0x0f, 0x12,
	0x16, 0x0a, 0x11, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x5f, 0x69, 0x64, 0x10, 0xd2, 0x0f, 0x12, 0x20, 0x0a, 0x1b, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x5f, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x5f,
	0x72, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x10, 0xd3, 0x0f, 0x12, 0x21, 0x0a, 0x1c, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x5f, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x69, 0x64, 0x10, 0xd4, 0x0f, 0x12, 0x15, 0x0a, 0x10,
	0x73, 0x65, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64,
	0x10, 0xd5, 0x0f, 0x12, 0x16, 0x0a, 0x11, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x69, 0x64, 0x10, 0xd6, 0x0f, 0x12, 0x15, 0x0a, 0x10, 0x72,
	0x65, 0x63, 0x76, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x6e, 0x74, 0x66, 0x5f, 0x69, 0x64, 0x10,
	0xd7, 0x0f, 0x12, 0x15, 0x0a, 0x10, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f,
	0x72, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x10, 0xd8, 0x0f, 0x12, 0x16, 0x0a, 0x11, 0x65, 0x78, 0x69,
	0x74, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x69, 0x64, 0x10, 0xd9,
	0x0f, 0x12, 0x1f, 0x0a, 0x1a, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x61, 0x6c,
	0x6c, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x10,
	0xda, 0x0f, 0x12, 0x20, 0x0a, 0x1b, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x61,
	0x6c, 0x6c, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x69,
	0x64, 0x10, 0xdb, 0x0f, 0x2a, 0xf6, 0x01, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x69,
	0x64, 0x12, 0x0c, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x6e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12,
	0x0f, 0x0a, 0x0b, 0x65, 0x72, 0x72, 0x5f, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x01,
	0x12, 0x15, 0x0a, 0x11, 0x65, 0x72, 0x72, 0x5f, 0x70, 0x61, 0x72, 0x73, 0x69, 0x6e, 0x67, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x10, 0x02, 0x12, 0x1a, 0x0a, 0x15, 0x65, 0x72, 0x72, 0x5f, 0x72,
	0x6f, 0x6f, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x10, 0xe9, 0x07, 0x12, 0x1a, 0x0a, 0x15, 0x65, 0x72, 0x72, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f,
	0x69, 0x64, 0x5f, 0x6e, 0x6f, 0x74, 0x5f, 0x65, 0x78, 0x69, 0x73, 0x74, 0x10, 0xea, 0x07, 0x12,
	0x27, 0x0a, 0x22, 0x65, 0x72, 0x72, 0x5f, 0x6f, 0x70, 0x74, 0x5f, 0x64, 0x69, 0x73, 0x61, 0x6c,
	0x6c, 0x6f, 0x77, 0x65, 0x64, 0x5f, 0x6e, 0x6f, 0x74, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x68,
	0x6f, 0x6c, 0x64, 0x65, 0x72, 0x10, 0xeb, 0x07, 0x12, 0x1f, 0x0a, 0x1a, 0x65, 0x72, 0x72, 0x5f,
	0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x69,
	0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0xd1, 0x0f, 0x12, 0x18, 0x0a, 0x13, 0x65, 0x72, 0x72,
	0x5f, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x63, 0x6c, 0x6f, 0x73, 0x65,
	0x10, 0xd2, 0x0f, 0x12, 0x18, 0x0a, 0x13, 0x65, 0x72, 0x72, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x6e,
	0x6e, 0x5f, 0x74, 0x6f, 0x6f, 0x5f, 0x6c, 0x61, 0x74, 0x65, 0x10, 0xb9, 0x17,
}

var (
	file_cs_proto_rawDescOnce sync.Once
	file_cs_proto_rawDescData = file_cs_proto_rawDesc
)

func file_cs_proto_rawDescGZIP() []byte {
	file_cs_proto_rawDescOnce.Do(func() {
		file_cs_proto_rawDescData = protoimpl.X.CompressGZIP(file_cs_proto_rawDescData)
	})
	return file_cs_proto_rawDescData
}

var file_cs_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cs_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_cs_proto_goTypes = []interface{}{
	(ProtoId)(0),                   // 0: main.proto_id
	(ErrorId)(0),                   // 1: main.error_id
	(*LoginReq)(nil),               // 2: main.login_req
	(*LoginResp)(nil),              // 3: main.login_resp
	(*GetAllRoomListReq)(nil),      // 4: main.get_all_room_list_req
	(*GetAllRoomListResp)(nil),     // 5: main.get_all_room_list_resp
	(*CreateRoomReq)(nil),          // 6: main.create_room_req
	(*RoomSettings)(nil),           // 7: main.room_settings
	(*CreateRoomResp)(nil),         // 8: main.create_room_resp
	(*DismissRoomReq)(nil),         // 9: main.dismiss_room_req
	(*DismissRoomResp)(nil),        // 10: main.dismiss_room_resp
	(*ChangeRoomSettingsReq)(nil),  // 11: main.change_room_settings_req
	(*ChangeRoomSettingsResp)(nil), // 12: main.change_room_settings_resp
	(*ChangeRoomSettingsNtf)(nil),  // 13: main.change_room_settings_ntf
	(*JoinRoomReq)(nil),            // 14: main.join_room_req
	(*JoinSettings)(nil),           // 15: main.join_settings
	(*GetRoomAllMemberReq)(nil),    // 16: main.get_room_all_member_req
	(*GetRoomAllMemberResp)(nil),   // 17: main.get_room_all_member_resp
	(*JoinRoomResp)(nil),           // 18: main.join_room_resp
	(*ChangeJoinSettingsReq)(nil),  // 19: main.change_join_settings_req
	(*ChangeJoinSettingsResp)(nil), // 20: main.change_join_settings_resp
	(*SendInfoReq)(nil),            // 21: main.send_info_req
	(*SendInfoResp)(nil),           // 22: main.send_info_resp
	(*RecvInfoNtf)(nil),            // 23: main.recv_info_ntf
	(*ExitRoomReq)(nil),            // 24: main.exit_room_req
	(*ExitRoomResp)(nil),           // 25: main.exit_room_resp
}
var file_cs_proto_depIdxs = []int32{
	0,  // 0: main.login_req.id:type_name -> main.proto_id
	0,  // 1: main.login_resp.id:type_name -> main.proto_id
	1,  // 2: main.login_resp.error:type_name -> main.error_id
	0,  // 3: main.get_all_room_list_req.id:type_name -> main.proto_id
	0,  // 4: main.get_all_room_list_resp.id:type_name -> main.proto_id
	7,  // 5: main.get_all_room_list_resp.rooms:type_name -> main.room_settings
	0,  // 6: main.create_room_req.id:type_name -> main.proto_id
	7,  // 7: main.create_room_req.settings:type_name -> main.room_settings
	0,  // 8: main.create_room_resp.id:type_name -> main.proto_id
	1,  // 9: main.create_room_resp.error:type_name -> main.error_id
	0,  // 10: main.dismiss_room_req.id:type_name -> main.proto_id
	0,  // 11: main.dismiss_room_resp.id:type_name -> main.proto_id
	1,  // 12: main.dismiss_room_resp.error:type_name -> main.error_id
	0,  // 13: main.change_room_settings_req.id:type_name -> main.proto_id
	7,  // 14: main.change_room_settings_req.settings:type_name -> main.room_settings
	0,  // 15: main.change_room_settings_resp.id:type_name -> main.proto_id
	1,  // 16: main.change_room_settings_resp.error:type_name -> main.error_id
	0,  // 17: main.change_room_settings_ntf.id:type_name -> main.proto_id
	7,  // 18: main.change_room_settings_ntf.settings:type_name -> main.room_settings
	0,  // 19: main.join_room_req.id:type_name -> main.proto_id
	15, // 20: main.join_room_req.settings:type_name -> main.join_settings
	0,  // 21: main.get_room_all_member_req.id:type_name -> main.proto_id
	0,  // 22: main.get_room_all_member_resp.id:type_name -> main.proto_id
	0,  // 23: main.join_room_resp.id:type_name -> main.proto_id
	1,  // 24: main.join_room_resp.error:type_name -> main.error_id
	0,  // 25: main.change_join_settings_req.id:type_name -> main.proto_id
	15, // 26: main.change_join_settings_req.settings:type_name -> main.join_settings
	0,  // 27: main.change_join_settings_resp.id:type_name -> main.proto_id
	1,  // 28: main.change_join_settings_resp.error:type_name -> main.error_id
	0,  // 29: main.send_info_req.id:type_name -> main.proto_id
	0,  // 30: main.send_info_resp.id:type_name -> main.proto_id
	1,  // 31: main.send_info_resp.error:type_name -> main.error_id
	0,  // 32: main.recv_info_ntf.id:type_name -> main.proto_id
	0,  // 33: main.exit_room_req.id:type_name -> main.proto_id
	0,  // 34: main.exit_room_resp.id:type_name -> main.proto_id
	1,  // 35: main.exit_room_resp.error:type_name -> main.error_id
	36, // [36:36] is the sub-list for method output_type
	36, // [36:36] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_cs_proto_init() }
func file_cs_proto_init() {
	if File_cs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllRoomListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllRoomListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomSettings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoomResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DismissRoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DismissRoomResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeRoomSettingsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeRoomSettingsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeRoomSettingsNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinSettings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoomAllMemberReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoomAllMemberResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRoomResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeJoinSettingsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeJoinSettingsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecvInfoNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExitRoomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cs_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExitRoomResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cs_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cs_proto_goTypes,
		DependencyIndexes: file_cs_proto_depIdxs,
		EnumInfos:         file_cs_proto_enumTypes,
		MessageInfos:      file_cs_proto_msgTypes,
	}.Build()
	File_cs_proto = out.File
	file_cs_proto_rawDesc = nil
	file_cs_proto_goTypes = nil
	file_cs_proto_depIdxs = nil
}
